[env]
CC = "/usr/bin/clang"
CXX = "/usr/bin/clang++"
CMAKE_C_COMPILER = "/usr/bin/clang"
CMAKE_CXX_COMPILER = "/usr/bin/clang++"
CXXFLAGS = "-stdlib=libc++"

[build]
rustflags = ["-C", "link-arg=-lc++", "-C", "link-arg=-lc++abi", "-C", "link-arg=-Wl,--allow-multiple-definition"]
