[package]
name = "tauri-plugin-positioner"
version = "2.3.1"
links = "tauri-plugin-positioner"
edition = "2021"
authors = ["Tauri Programme within The Commons Conservancy"]
description = "Position your windows at well-known locations."
license = "Apache-2.0 OR MIT"

[lib]
name = "tauri_plugin_positioner"
path = "src/lib.rs"

[features]
tray-icon = ["tauri/tray-icon"]

[dependencies]
log = "0.4"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
serde_repr = "0.1"
tauri = { version = "2", default-features = false }
thiserror = "2"

[build-dependencies]
tauri-plugin = { version = "2", features = ["build"] }
